name: 'Deploying on s3 bucket'
description: 'deploying application on s3 bucket'

inputs:
  bucket:
    description: 'bucket name'
    required: true
  bucket-region:
    description: 'bucket bucket-region'
    required: false 
    default: 'eu-west-1'
  dist-folder:
    description: 'files folder'
    required: true
  
runs:
  using: 'docker'
  image: Dockerfile